name: flutter_app
description: "Crypto App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.0.6
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  talker_flutter: ^4.9.0
  talker_dio_logger: ^4.9.0
  talker_bloc_logger: ^4.6.4
  firebase_core: ^3.14.0
  json_annotation: ^4.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_route: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  auto_route_generator: ^8.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/nature.jpeg
     - assets/bitcoinpng.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
