// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvk1EVxoKFs654XKmZNs9-osojY07-chA',
    appId: '1:822075275906:web:cf1505ef72ca7555a7529b',
    messagingSenderId: '822075275906',
    projectId: 'cryptolistapp',
    authDomain: 'cryptolistapp.firebaseapp.com',
    storageBucket: 'cryptolistapp.firebasestorage.app',
    measurementId: 'G-MBF8M1MJ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAX1l0Pv5N2_NQD3O1sk5IYv_WsJN9hHg',
    appId: '1:822075275906:android:10e7376f1259b4dba7529b',
    messagingSenderId: '822075275906',
    projectId: 'cryptolistapp',
    storageBucket: 'cryptolistapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtsLvqRF-ot7So54D5jfthdErmwqg25nA',
    appId: '1:822075275906:ios:87dd8280807a342ca7529b',
    messagingSenderId: '822075275906',
    projectId: 'cryptolistapp',
    storageBucket: 'cryptolistapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
}
